### ISSUE TITLE
invalid multibyte char (US-ASCII) (SyntaxError)

### ISSUE THREAD

**Issue by donatoaz** [hisea/devise-bootstrap-views#18] opened 2015-07-04 19:05 UTC
There seems to be some sort of encoding issue with the devise_bootstrap_views_helper.rb file.

I had to manually add:

  #!/bin/env ruby
  # encoding: utf-8

To the top of the file to get it to work.

rails 4.0.2
ruby ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-darwin10.8.0]

**Comment by isseu** [comment] 2015-07-09 20:11
I have the same problem

**Comment by crab-apple** [comment] 2015-08-18 15:32
I too have the same problem. It seems to be caused by the "cross character" (⨉) in this line:

``` html
<button type="button" class="close" data-dismiss="alert">⨉</button>
```

**Comment by PFischbeck** [comment] 2015-09-08 21:38
This seems to be fixed by the PRs #22 and #23, but we will have to wait until the next release in order to receive the patch. Until then, this will be broken on Ruby 1.9.

**Comment by hisea** [comment] 2015-09-09 01:42
Sorry for the delay but just made a release. now 0.0.6 should contain the unicode fix.

**Closed as completed by hisea** 2015-09-09 01:42 UTC

**Comment by PFischbeck** [comment] 2015-09-09 10:11
Thanks!

**Comment by isseu** [comment] 2015-09-11 23:28
Thanks!
